# Generated by Django 5.1.5 on 2025-02-16 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='publications_flag',
            field=models.BooleanField(default=False, verbose_name='Признак публикации(булевое значение)'),
        ),
    ]
