# Generated by Django 5.1.5 on 2025-02-16 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'category', 'created_at', 'updated_at'), 'permissions': (('can_cancel_product', 'Can cancel product'),), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
