# Generated by Django 5.1.5 on 2025-02-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('price', 'category', 'created_at', 'updated_at'), 'permissions': (('can_unpublish_product', 'Can unpublish product'),), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
